# Production Stage
FROM nginx:alpine

# Copy built assets from local build
COPY dist /usr/share/nginx/html

# Overwrite default nginx config to handle client side routing
RUN echo 'server { \
    listen 80; \
    location / { \
    root   /usr/share/nginx/html; \
    index  index.html index.htm; \
    try_files $uri $uri/ /index.html; \
    } \
    }' > /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
